### ISSUE TITLE
ConsultaCEP - Webservice Correios

### ISSUE THREAD

**Issue by guiserinoli** [m2-systemcode/BrazilCustomerAttributes#26]
Boa tarde Eduardo.
Aparentemente a consulta de CEP feita pelo Webservice dos Correios, que ocorre no Consult/Address.php, está apresentando constantes Timeout's. Talvez seja o caso de trocar esta consulta, talvez para a solução da Republica Virtual (http://www.republicavirtual.com.br/busca_de_cep/PHP/#php). Houve mais relatos dessa falha?

**Comment by netembalagens** [comment]
Fizemos uma modificação, mas estamos testando ainda...

app/code/SystemCode/BrazilCustomerAttributes/Controller/Consult/Address.php

`
public function execute()
    {
        $data = ["error" => false];

        // Alternativa para não demorar tanto
        $zipcode = $this->getRequest()->getParam('zipcode');
        $data = (array) json_decode(file_get_contents('http://cep.republicavirtual.com.br/web_cep.php?cep='.$zipcode.'&formato=jsonp'));
        $xLogra = explode('- de ',$data['logradouro']);
        if(count($xLogra)>=2){
            $data['logradouro'] = $xLogra[0];
        }
        $scope = [
            'neighborhood'=>$data['bairro'],
            'street'=>$data['tipo_logradouro'].' '.$data['logradouro'],
            'city'=>$data['cidade'],
            'uf'=>$data['uf'],
            'zipcode'=>$zipcode,
            'error'=>false
        ];
        $return = $this->_resultJsonFactory->create();
        return $return->setData($scope);
}

`

**Comment by eduardoddias** [comment]
Sim, esta até no TODO do módulo. A ideia seria manter a atual (mas deixando ela como secundária) e utilizar a da republica virtual como primária...

**Comment by guiserinoli** [comment]
Olá Eduardo. Creio que esta questão poderia ser tratada com prioridade, o WebService dos Correios realmente está falhando o tempo todo. De qualquer forma, ótimo saber que já está no backlog de vocês. Abs

**Comment by guiserinoli** [comment]
Olá pessoal, alguma novidade com relação à este caso? Talvez algum esboço de modificação, como informado pelo @netembalagens.

**Comment by robsoned** [comment]
@guiserinoli  Na PR #35 a consulta está sendo feita no webservice ViaCep, e a dos correios está em segundo plano

**Comment by eduardoddias** [comment]
@robsoned, não vejo a necessidade de utilizar as dependências jansenfelipe/cep-gratis e
guzzlehttp/guzzle... Acredito que a melhor forma seja essa:
https://webkul.com/blog/use-curl-magento-2/

**Comment by robsoned** [comment]
@eduardoddias A do jansenfelipe/cep-gratis eu já havia removido. Vou dar uma olhada no curl do magento 2

**Comment by robsoned** [comment]
@eduardoddias Foi removida as dependências e a consulta viacep está sendo feita com o curl do Framework do Magento 2.
 #35

**Comment by eduardoddias** [comment]
Foi implementado a dependência do módulo magedev/brazilzipcode do @wallycofe sanando esse problema.
