### ISSUE TITLE
Funiona na versão 2.3.4?

### ISSUE THREAD

**Issue by awakebrasil** [m2-systemcode/BrazilCustomerAttributes#46]
Estou testando aqui e o auto completar no checkout não preenche e não da nenhum erro no log.

**Comment by MaxSouza** [comment]
Estamos efetuando os testes na versão 2.3.5, em breve estará 100%

**Comment by gutomissiatto-git** [comment]
Olá utilizo na 2.3.4 tranquilamente, somente o auto completar que as vezes não carrega o preenchimento automático.
Uma dúvida que tenho, é possível colocar todos os campos como obrigatórios, exemplo, endereço, bairro, cidade, cep.. Se não for possível, seria uma sugestão colocar.

**Comment by eduardoddias** [comment]
Bug relacionado a issue #26
