### ISSUE TITLE
[BUG] Deprecated Functionality: Array and string offset quando compilando

### ISSUE THREAD

**Issue by r-martins** [m2-systemcode/BrazilCustomerAttributes#54]
### Precondições (*)

1. BrazilCustomerAttributes 1.1.0
2. Magento 2.4.0
3. PHP 7.4

### Passos para reproduzir (*)
1. Instalar manualmente os modulos base e este (via composer deu problema no magento 2.4)
2. Rodar `setup:di:compile`

### Resultado esperado (*)
1. Compilação bem sucedida

### Resultado ocorrido (*)
Erro

> Deprecated Functionality: Array and string offset access syntax with curly braces is deprecated in .../magento240/app/code/SystemCode/BrazilCustomerAttributes/Helper/Data.php on line 48

**Comment by eduardoddias** [comment]
Obrigado pela contribuição @r-martins
