### ISSUE TITLE
Previsão pra rodar na versão 2.4.0?

### ISSUE THREAD

**Issue by irnjunior** [m2-systemcode/BrazilCustomerAttributes#61]
Tentei instalar em um ambiente de desenvolvimento na versão 2.4.0 mas ele diz que a versão do PHP é impcompatível.

` requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.3.22)`

**Comment by eduardoddias** [comment]
@irnjunior, provavelmente esse final de semana... temporariamente você pode rodar o comando do composer com:
`--ignore-platform-reqs `

**Comment by eduardoddias** [comment]
@irnjunior o erro foi corrigido, caso o problema persista, execute o seguinte comando para limpar a cache do composer:
`composer cc`

**Comment by irnjunior** [comment]
Parece estar funcionando 100%. Obrigado!
